### ISSUE TITLE
[doc] Add aws required permission list

### ISSUE THREAD

**Issue by flyisland** [SolaceProducts/pubsubplus-aws-ha-quickstart#18]
I keep accounting error like " is not authorized to perform: iam:PassRole on resource". It'd be better has a permission list in the guide.

**Comment by KenBarr** [comment]
In the source you can look for AWS::IAM::Role

From Solace templates you can see the following roles:
s3:GetObject <- used to read templates from S3 buckets
cloudformation:DescribeStackResources <- used to reflexively look at the current and parent stacks
ec2:DescribeInstances <- used to find IP addresses of peer nodes in the cluster
ec2:CreateTags <- add the names to the EC2 instances

From AWS templates you can see in the Bastion template:
s3:GetObject <- used to read templates from S3 buckets
logs:CreateLogStream <- used for cloudwatch logging
logs:GetLogEvents
logs:PutLogEvents
logs:DescribeLogGroups
logs:DescribeLogStreams
logs:PutRetentionPolicy
logs:PutMetricFilter
logs:CreateLogGroup
ec2:AssociateAddress  <- map EIP to host
ec2:DescribeAddresses
