### ISSUE TITLE
Outdated Docker Create Configuration

### ISSUE THREAD

**Issue by deskoh** [SolaceProducts/pubsubplus-aws-ha-quickstart#43]
The line below no longer seemed to be valid:

https://github.com/SolaceProducts/solace-aws-ha-quickstart/blob/769b74f02680a150ff07bd2a4f70e79f2f8bd1b6/scripts/install-solace.sh#L295

`redundancy_group_passwordfilepath` seemed to be replaced by `redundancy_authentication_presharedkey_keyfilepath`.

Also, the value required be should be a base64 encoded value of binary data with 32 to 256 bytes length.

Reference:
https://docs.solace.com/Configuring-and-Managing/SW-Broker-Specific-Config/Docker-Tasks/Config-SW-Broker-Container-Cfg-Keys.htm
https://docs.solace.com/Configuring-and-Managing/SW-Broker-Specific-Config/Docker-Tasks/HA-Config/HA-Docker-Windows.htm
https://docs.solace.com/Configuring-and-Managing/Configuring-HA-Groups.htm

**Comment by bczoma** [comment]
Thanks for raising Desmond, will revise. The current way still works in legacy mode but is indeed outdated.

**Comment by PhilippeKhalife** [comment]
Fixed with latest PR.
