### ISSUE TITLE
Optimize TCP for WAN

### ISSUE THREAD

**Issue by KenBarr** [SolaceProducts/pubsubplus-aws-ha-quickstart#7]
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 25165824 67108864
net.ipv4.tcp_wmem = 4096 25165824 67108864
net.ipv4.tcp_mtu_probing=1

**Comment by PhilippeKhalife** [comment]
This work is completed.
